version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nestmatch_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: nestmatch_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nestmatch_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nestmatch_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestmatch_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgrespassword@postgres:5432/nestmatch_db
      - REDIS_URL=redis://redis:6379/0
      - APP_ENV=development
      - SECRET_KEY=e839e94474775d0a6bb81efca3b069d25a81615f3813a846c2faea7e9f3b1402
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app

volumes:
  pgdata:
  redisdata:
